name: deploy to production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install node_modules
        run: npm ci
      - name: build and deploy to directpodcast.fr
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          REACT_APP_RECAPTCHA_CLIENT_SIDE: ${{ secrets.REACT_APP_RECAPTCHA_CLIENT_SIDE }}
          REACT_APP_RECAPTCHA_SERVER_SIDE: ${{ secrets.REACT_APP_RECAPTCHA_SERVER_SIDE }}
          NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
          NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run deploy
